export const REQUIRED_OBJECT_TYPES = {
    CAMERA: "CAMERA",
    RENDERER: "RENDERER",
    SCENE: "SCENE",
    ORBIT_CONTROLLER: "ORBIT_CONTROLLER",
    SIZES: "SIZES",
    DEBUGGER: "DEBUGGER",
    CANVAS: "CANVAS"
}
