export const REQUIRED_OBJECT_TYPES = {
    CAMERA: "CAMERA",
    RENDERER: "RENDERER",
    SCENE: "SCENE",
    ORBIT_CONTROLLER: "ORBIT_CONTROLLER",
    SIZES: "SIZES",
    DEBUGGER: "DEBUGGER"
}

export const WORLD_OBJECT_GEOMETRIES = {
    PLANE: "PLANE",
    BOX: "BOX"
}

export const WORLD_OBJECT_MESH_TYPES = {
    STANDARD: "STANDARD",
    BASIC: "BASIC"
}